/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist AggregateType
 */
public enum AggregateTypeEnum {

    // Avg
    AVG("Avg"),
    // Count
    COUNT("Count"),
    // Sum
    SUM("Sum");

    final String value;

    private AggregateTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AggregateTypeEnum fromValue(String value) {
        for (AggregateTypeEnum e : AggregateTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
