/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Format
 */
public enum FormatEnum {

    // CSS
    CSS("CSS"),
    // JS
    JS("JS"),
    // SVG
    SVG("SVG"),
    // TEMPLATE_CSS
    TEMPLATE_CSS("TEMPLATE_CSS"),
    // XML
    XML("XML");

    final String value;

    private FormatEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
        for (FormatEnum e : FormatEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
