/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist IdentityMapping
 */
public enum IdentityMappingEnum {

    // FederationId
    FEDERATIONID("FederationId"),
    // UserId
    USERID("UserId"),
    // Username
    USERNAME("Username");

    final String value;

    private IdentityMappingEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static IdentityMappingEnum fromValue(String value) {
        for (IdentityMappingEnum e : IdentityMappingEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
