/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist InvocationStatus
 */
public enum InvocationStatusEnum {

    // Failed
    FAILED("Failed"),
    // New
    NEW("New"),
    // Pending
    PENDING("Pending"),
    // Successful
    SUCCESSFUL("Successful");

    final String value;

    private InvocationStatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static InvocationStatusEnum fromValue(String value) {
        for (InvocationStatusEnum e : InvocationStatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
