/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Operation
 */
public enum OperationEnum {

    // Activate
    ACTIVATE("Activate"),
    // Create
    CREATE("Create"),
    // Deactivate
    DEACTIVATE("Deactivate"),
    // Freeze
    FREEZE("Freeze"),
    // Linking
    LINKING("Linking"),
    // Read
    READ("Read"),
    // Reconcile
    RECONCILE("Reconcile"),
    // Unfreeze
    UNFREEZE("Unfreeze"),
    // Update
    UPDATE("Update");

    final String value;

    private OperationEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static OperationEnum fromValue(String value) {
        for (OperationEnum e : OperationEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
