/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ProviderType
 */
public enum ProviderTypeEnum {

    // Facebook
    FACEBOOK("Facebook"),
    // GitHub
    GITHUB("GitHub"),
    // Google
    GOOGLE("Google"),
    // Janrain
    JANRAIN("Janrain"),
    // LinkedIn
    LINKEDIN("LinkedIn"),
    // MicrosoftACS
    MICROSOFTACS("MicrosoftACS"),
    // OpenIdConnect
    OPENIDCONNECT("OpenIdConnect"),
    // Salesforce
    SALESFORCE("Salesforce"),
    // Twitter
    TWITTER("Twitter");

    final String value;

    private ProviderTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ProviderTypeEnum fromValue(String value) {
        for (ProviderTypeEnum e : ProviderTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
