/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type BusinessProcess
 */
public class QueryRecordsBusinessProcess extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<BusinessProcess> records;

    public List<BusinessProcess> getRecords() {
        return records;
    }

    public void setRecords(List<BusinessProcess> records) {
        this.records = records;
    }
}
