/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Reason
 */
public enum ReasonEnum {

    // Breakdown
    BREAKDOWN("Breakdown"),
    // Equipment Complexity
    EQUIPMENT_COMPLEXITY("Equipment Complexity"),
    // Equipment Design
    EQUIPMENT_DESIGN("Equipment Design"),
    // Feedback
    FEEDBACK("Feedback"),
    // Installation
    INSTALLATION("Installation"),
    // Other
    OTHER("Other"),
    // Performance
    PERFORMANCE("Performance");

    final String value;

    private ReasonEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ReasonEnum fromValue(String value) {
        for (ReasonEnum e : ReasonEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
