/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 29 00:57:07 BRST 2016
 */
package com.redhat.gpe.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist State
 */
public enum StateEnum {

    // Analyzed
    ANALYZED("Analyzed"),
    // Analyzing
    ANALYZING("Analyzing"),
    // Collected
    COLLECTED("Collected"),
    // Collecting
    COLLECTING("Collecting"),
    // Committing
    COMMITTING("Committing"),
    // Completed
    COMPLETED("Completed"),
    // Failed
    FAILED("Failed"),
    // New
    NEW("New"),
    // Requested
    REQUESTED("Requested");

    final String value;

    private StateEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
        for (StateEnum e : StateEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
